name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main    # production
      - dev     # development

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: pnpm install

      - name: Generate version and write to public/version.json
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          TS=$(date -u +'%Y.%m.%d.%H%M%S')
          BRANCH="${GITHUB_REF_NAME:-${GITHUB_REF##*/}}"
          VERSION="$TS-$SHORT_SHA"
          if [ "$BRANCH" != "main" ]; then
            VERSION="$BRANCH-$VERSION"
          fi
          echo "APP_VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "{\"version\":\"$VERSION\"}" > public/version.json

      - run: pnpm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: ${{ github.ref == 'refs/heads/main' && 'live' || 'dev' }}
          projectId: allwork-e32b6
